# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# pyre-strict

"""In-allocation runner for ``SlurmJob`` batch mode.

Invoked as the body of the sbatch script generated by
``apply(client_script=...)``. Runs on the head node and:

  1. seeds a worker on every node (one task per node),
  2. runs the client with ``MONARCH_BATCH_JOB=1`` so its cached ``BatchJob``
     reconnects to this allocation,
  3. terminates the workers in a ``finally``.

When this process exits the allocation is freed with the client's exit status.
"""

import argparse
import ipaddress
import os
import shlex
import subprocess
import sys
from typing import List, Optional

from monarch._src.job._batch_env import MONARCH_BATCH_JOB_ENV


# Bootstraps one Monarch worker that advertises this node's hostname. Passed as
# Python ``-c`` argv (no shell), so quoting inside is irrelevant.
_WORKER_BOOTSTRAP: str = (
    "import os, socket; from monarch.actor import run_worker_loop_forever; "
    "from monarch._src.job.service_identity import service_proc_addr, ranked_service_proc_id_from_env; "
    'run_worker_loop_forever(address=service_proc_addr(f"%s", '
    'ranked_service_proc_id_from_env(rank_env="SLURM_NODEID")), '
    'ca="trust_all_connections")'
)


def _worker_bootstrap(
    port: int, bind_to: Optional[str], setup: Optional[str] = None
) -> str:
    address = f"tcp://{{socket.gethostname()}}:{port}"
    if bind_to is not None:
        bind_ip = ipaddress.ip_address(bind_to)
        bind_host = f"[{bind_ip}]" if bind_ip.version == 6 else str(bind_ip)
        address += f"@tcp://{bind_host}:{port}"
    bootstrap = _WORKER_BOOTSTRAP % address
    # Setup runs first, before the bootstrap imports monarch. A newline (not
    # "; ") keeps the bootstrap out of a trailing compound statement.
    return bootstrap if setup is None else f"{setup}\n{bootstrap}"


def main(argv: Optional[List[str]] = None) -> None:
    parser = argparse.ArgumentParser(prog="monarch._src.job._slurm_batch")
    parser.add_argument("--port", type=int, default=22222)
    parser.add_argument("--bind-to")
    parser.add_argument("--worker-setup")
    parser.add_argument("client", help="client command to run inside the allocation")
    args = parser.parse_args(argv)

    # No warmup wait: the client's attach retries with backoff, so workers that
    # are still booting are handled by the channel layer, not a sleep here.
    workers = subprocess.Popen(
        [
            "srun",
            "--ntasks-per-node=1",
            sys.executable,
            "-c",
            _worker_bootstrap(args.port, args.bind_to, args.worker_setup),
        ]
    )
    try:
        env = dict(os.environ, **{MONARCH_BATCH_JOB_ENV: "1"})
        returncode = subprocess.run(shlex.split(args.client), env=env).returncode
    finally:
        if workers.poll() is None:
            workers.terminate()
            try:
                workers.wait(timeout=30)
            except subprocess.TimeoutExpired:
                workers.kill()
    sys.exit(returncode)


if __name__ == "__main__":
    main()
